# services/memory_manager.py
#
# MemoryManager — orchestrates short-term (Redis) + mid-term (chunks) + long-term (Mongo) memory.
#
# Responsibilities:
#   - Load context from Redis sliding window, fallback to Mongo
#   - Inject chunk summaries so context never "loses" older context
#   - Store messages to both Mongo and Redis
#   - Trigger and route summarization when thresholds are met
#
# Does NOT own DB schema — only calls existing helpers from db/ module.

import logging
import asyncio
from utils.token_counter import count_tokens
from db.mongo_helpers import (
    get_last_messages,
    get_chat_by_id,
    insert_message,
    get_summary_chunks,
)
from db.redis_helpers import (
    push_recent_message,
    get_recent_messages,
    enqueue_summarization_job,
    acquire_summarization_lock,
    release_summarization_lock,
    get_cached_chat_summary,
    set_cached_chat_summary,
)

logger = logging.getLogger(__name__)

# ── Summarization thresholds ──────────────────────────────────────────────
SUMMARIZE_TOKEN_THRESHOLD = 10_000    # totalTokens > 10K
SUMMARIZE_MSG_THRESHOLD = 80          # messageCount > 80


class MemoryManager:
    """
    Manages chat memory lifecycle:
      1. Load context (Redis hot → chunk summaries → Mongo cold fallback)
      2. Store new messages (Mongo + Redis)
      3. Check & enqueue summarization when needed
    """

    def __init__(self, db, redis):
        self.db    = db
        self.redis = redis

    # ── Load Context ──────────────────────────────────────────────────

    async def load_context(self, chat_id: str, chat_doc: dict | None = None) -> dict:
        """
        Load conversation context for building the LLM payload.

        Strategy:
          1. Try Redis sliding window first (30 most recent)
          2. Try Redis cached summary
          3. If everything is hot, return immediately (ZERO Mongo reads)
          4. Fall back to Mongo if any part is missing
        """
        # 1. Try Redis (hot path) — FASTEST
        try:
            # We use asyncio.gather to check both Redis keys in parallel
            recent_task = get_recent_messages(self.redis, chat_id)
            cached_summ_task = get_cached_chat_summary(self.redis, chat_id)
            recent, cached_summ = await asyncio.gather(recent_task, cached_summ_task)

            if recent and cached_summ:
                return {
                    "messages":       recent,
                    "summary":        cached_summ["summary"],
                    "summary_tokens": cached_summ["tokens"],
                    "source":         "redis",
                }
            
            # If we have messages but no summary (or vice-versa), we continue to Mongo 
            # to reconstruct the state and fix the cache.
            if recent:
                # Part-hot: Fetch/build summary, then return
                summary, tokens = await self._build_summary_context(chat_id, chat_doc=chat_doc)
                return {
                    "messages":       recent,
                    "summary":        summary,
                    "summary_tokens": tokens,
                    "source":         "redis",
                }
        except Exception as e:
            logger.warning(f"Redis read failed in load_context for chat {chat_id}: {e}")

        # 2. Fallback to Mongo (cold path)
        if not chat_doc:
            chat_doc = await get_chat_by_id(self.db, chat_id)
        
        summary, summary_tokens = await self._build_summary_context(chat_id, chat_doc=chat_doc)

        messages = await get_last_messages(self.db, chat_id, limit=30)
        formatted = [
            {
                "role":    msg["role"],
                "content": msg["content"],
                "tokens":  msg.get("tokens", 0),
            }
            for msg in messages
        ]

        # Warm up Redis (Concurrent Batch Push)
        if formatted:
            try:
                # push_recent_message handles LTRIM
                await asyncio.gather(*[
                    push_recent_message(self.redis, chat_id, msg) for msg in formatted
                ])
            except Exception as e:
                logger.warning(f"Failed to warm Redis cache for chat {chat_id}: {e}")

        return {
            "messages":       formatted,
            "summary":        summary,
            "summary_tokens": summary_tokens,
            "source":         "mongo",
        }

    async def _build_summary_context(self, chat_id: str, chat_doc: dict | None = None, token_budget: int = 2000):
        """
        Build the summary context to inject above the recent messages.

        Priority:
          1. chats.summary  — meta-summary generated by worker
          2. Concatenate individual chunks — up to token_budget
        """
        if not chat_doc:
            chat_doc = await get_chat_by_id(self.db, chat_id)
        
        if not chat_doc:
            logger.warning(f"Chat {chat_id} not found while building summary context.")
            return None, 0

        # High priority: Meta-summary (merged view)
        meta_summary = chat_doc.get("summary")
        if meta_summary:
            summary, tokens = meta_summary, chat_doc.get("summaryTokens", 0)
            # Update Redis cache while we're here
            asyncio.create_task(set_cached_chat_summary(self.redis, chat_id, summary, tokens))
            return summary, tokens

        # Low priority Fallback: Concatenate individual recent chunks
        try:
            chunks = await get_summary_chunks(self.db, chat_id, limit=10)
            if not chunks:
                return None, 0

            preserved_chunks = []
            current_tokens = 0
            
            for c in chunks:
                chunk_text = f"[Earlier conversation segment {c['chunkIndex'] + 1}]\n{c['summary']}"
                chunk_tokens = c.get("tokens") or count_tokens(chunk_text)
                
                if current_tokens + chunk_tokens > token_budget:
                    break
                
                preserved_chunks.append(chunk_text)
                current_tokens += chunk_tokens

            if preserved_chunks:
                combined = "\n\n---\n\n".join(preserved_chunks)
                # Update Redis cache
                asyncio.create_task(set_cached_chat_summary(self.redis, chat_id, combined, current_tokens))
                return combined, current_tokens

        except Exception as e:
            logger.error(f"Failed to load summary chunks for chat {chat_id}: {e}", exc_info=True)

        return None, 0

    # ── Store Message ─────────────────────────────────────────────────

    async def store_message(
        self, chat_id: str, user_id: str, role: str, content: str, tokens: int, attachments: list | None = None
    ):
        """
        Store a message to both Mongo (persistent) and Redis (hot cache).
        insert_message in mongo_helpers also atomically increments
        chat stats and user token stats.
        """
        # 1. Persist to Mongo (source of truth)
        msg_id = await insert_message(
            self.db, chat_id, user_id, role, content, tokens, attachments=attachments
        )

        # 2. Push to Redis sliding window (best-effort)
        try:
            payload = {
                "id":      str(msg_id),
                "role":    role,
                "content": content,
                "tokens":  tokens,
            }
            if attachments:
                # Safety: Store only metadata in Redis window to prevent memory bloat
                # raw binary/base64 data should never be pushed to Redis lists
                safe_attachments = []
                for a in attachments:
                    safe_attachments.append({
                        "filename":     a.get("filename"),
                        "url":          a.get("url"),
                        "content_type": a.get("content_type")
                    })
                payload["attachments"] = safe_attachments

            await push_recent_message(self.redis, chat_id, payload)
        except Exception as e:
            logger.warning(f"Failed to push to Redis window for chat {chat_id}: {e}")

        return msg_id

    # ── Summarization ─────────────────────────────────────────────────

    async def check_summarization_needed(self, chat_id: str, chat_doc: dict | None = None) -> bool:
        """
        Check if a chat needs summarization.
        Triggers when totalTokens > 10K OR messageCount > 80.
        """
        if not chat_doc:
            chat_doc = await get_chat_by_id(self.db, chat_id)
        
        if not chat_doc:
            return False

        return (
            chat_doc.get("totalTokens", 0) > SUMMARIZE_TOKEN_THRESHOLD
            or chat_doc.get("messageCount", 0) > SUMMARIZE_MSG_THRESHOLD
        )

    async def enqueue_summarization(self, chat_id: str, chat_doc: dict | None = None):
        """
        Enqueue a summarization job for background processing.

        Atomic Guard: Uses SET NX summarization lock to ensure 
        only ONE background job exists for a chat at any time.
        """
        try:
            # 1. Atomic Check-and-Set Lock
            # This ensures only ONE background job exists for a chat at any time.
            locked = await acquire_summarization_lock(self.redis, chat_id)
            if not locked:
                return

            # 2. Fetch doc if not provided (needed for snapshot)
            if not chat_doc:
                chat_doc = await get_chat_by_id(self.db, chat_id)
            
            if not chat_doc:
                await release_summarization_lock(self.redis, chat_id)
                return

            # 3. Build snapshot and enqueue
            snapshot = {
                "totalTokens":  chat_doc.get("totalTokens", 0),
                "messageCount": chat_doc.get("messageCount", 0),
            }
            await enqueue_summarization_job(self.redis, chat_id, snapshot)
            logger.info(f"Enqueued summarization job for chat {chat_id}")

        except Exception as e:
            logger.error(f"Failed to enqueue summarization for chat {chat_id}: {e}")
            # If we failed before RPUSH, try to release the lock so we don't block future attempts
            try:
                await release_summarization_lock(self.redis, chat_id)
            except:
                pass
